/**
 * Kit formulas — V1 hardcoded
 *
 * Each slot defines:
 *  - label: user-facing name in the kit
 *  - categorySlug: maps to categories.slug in the DB
 *  - brand: optional brand filter
 *  - qty: default quantity of this item in the kit
 *  - priceHint: 'low' picks cheapest in stock, 'high' picks most expensive
 *  - role: what this component does (for the description badge)
 */

export type PriceHint = 'low' | 'mid' | 'high'
export type KitScale = 'S' | 'M' | 'L'
export type ScenarioId = 'oficina' | 'hogar' | 'tienda' | 'negocio' | 'colegio' | 'almacen'

export interface KitSlot {
  id: string
  label: string
  role: string
  categorySlug: string
  brand?: string
  qty: number
  priceHint: PriceHint
  optional?: boolean
}

export interface KitScaleConfig {
  name: string
  description: string
  slots: KitSlot[]
}

export interface ScenarioConfig {
  id: ScenarioId
  label: string
  icon: string
  description: string
  color: string // Tailwind bg class
  accent: string // Tailwind text class
  scales: Record<KitScale, KitScaleConfig>
}

// ─── FORMULAS ────────────────────────────────────────────────────────────────

export const KIT_FORMULAS: ScenarioConfig[] = [
  {
    id: 'oficina',
    label: 'Oficina',
    icon: '🏢',
    description: 'Vigilancia y conectividad para espacios de trabajo',
    color: 'bg-blue-50',
    accent: 'text-blue-700',
    scales: {
      S: {
        name: 'Oficina Pequeña',
        description: 'Hasta 3 personas, un solo ambiente. Cobertura interior básica.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara Interior',
            role: 'Vigilancia interior',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Conectividad',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS / Respaldo',
            role: 'Protección eléctrica',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'low',
          },
        ],
      },
      M: {
        name: 'Oficina Mediana',
        description: 'Hasta 10 personas, 2–3 ambientes. Entrada, sala y pasillo cubiertos.',
        slots: [
          {
            id: 'cam-int-1',
            label: 'Cámara Interior',
            role: 'Vigilancia interior',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara Exterior / PTZ',
            role: 'Vigilancia acceso externo',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Conectividad principal',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS / Respaldo',
            role: 'Protección eléctrica',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Oficina Grande',
        description: 'Más de 10 personas, múltiples pisos. Cobertura total con NVR y red PoE.',
        slots: [
          {
            id: 'cam-int-1',
            label: 'Cámara Interior',
            role: 'Vigilancia interior',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara Exterior / PTZ',
            role: 'Vigilancia perímetro',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR Grabador',
            role: 'Almacenamiento centralizado',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Conectividad principal',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'ups',
            label: 'UPS / Respaldo',
            role: 'Protección eléctrica',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'mid',
          },
        ],
      },
    },
  },
  {
    id: 'hogar',
    label: 'Hogar',
    icon: '🏠',
    description: 'Seguridad inteligente para tu casa',
    color: 'bg-emerald-50',
    accent: 'text-emerald-700',
    scales: {
      S: {
        name: 'Apartamento / Casa pequeña',
        description: 'Hasta 2 habitaciones. Entrada principal y sala.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara Interior 360°',
            role: 'Sala / área común',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'cam-ext',
            label: 'Cámara Exterior',
            role: 'Entrada y jardín',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS Mini',
            role: 'Respaldo router y cámaras',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'low',
          },
        ],
      },
      M: {
        name: 'Casa mediana',
        description: '3–4 habitaciones. Entradas, jardín y garaje cubiertos.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara Interior',
            role: 'Interior y pasillos',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara Exterior',
            role: 'Entrada y garaje',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red hogar',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS Respaldo',
            role: 'Alimenta router y NVR',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Casa grande / Finca',
        description: '+5 habitaciones o exterior amplio. Cobertura completa con grabación.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara Interior',
            role: 'Interior y accesos',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 3,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara Exterior PTZ',
            role: 'Perímetro y exteriores',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 3,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR Grabador',
            role: 'Almacenamiento 24/7',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red principal',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS Respaldo',
            role: 'Protección eléctrica',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
    },
  },
  {
    id: 'tienda',
    label: 'Tienda',
    icon: '🏪',
    description: 'Vigilancia de punto de venta y acceso de clientes',
    color: 'bg-violet-50',
    accent: 'text-violet-700',
    scales: {
      S: {
        name: 'Tienda pequeña',
        description: 'Local de hasta 50m². Caja registradora, vitrina y entrada.',
        slots: [
          {
            id: 'cam-caja',
            label: 'Cámara caja / mostrador',
            role: 'Sobre caja registradora',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'low',
          },
          {
            id: 'cam-ext',
            label: 'Cámara entrada',
            role: 'Control de acceso',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red local y pagos',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Uptime del sistema',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'low',
          },
        ],
      },
      M: {
        name: 'Tienda mediana',
        description: '50–150m². Cobertura de bodega, ventas y entrada.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Pasillo y estantes',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 3,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior',
            role: 'Entrada y fachada',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red comercial',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Respaldo continuo',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Supermercado / Local grande',
        description: '+150m². Múltiples pasillos, bodegas y estacionamiento.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Pasillos y refrigeración',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 6,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Parqueadero y fachada',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 3,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR grabador',
            role: 'Grabación 24/7',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi Pro',
            role: 'Red de datos',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'ups',
            label: 'UPS Mediana',
            role: 'Respaldo crítico',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'mid',
          },
        ],
      },
    },
  },
  {
    id: 'negocio',
    label: 'Negocio',
    icon: '🏭',
    description: 'Bodegas, talleres y negocios con mayor flujo',
    color: 'bg-amber-50',
    accent: 'text-amber-700',
    scales: {
      S: {
        name: 'Negocio básico',
        description: 'Taller o bodega pequeña. Interior y acceso principal.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Área de trabajo',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior',
            role: 'Entrada y cargue',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Conectividad',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Respaldo equipos',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      M: {
        name: 'Negocio mediano',
        description: 'Múltiples áreas de trabajo y bodega.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Producción y bodega',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Accesos y patio',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red empresarial',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS Mediana',
            role: 'Respaldo sistema',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Empresa grande',
        description: 'Nave industrial o empresa con múltiples accesos y turnos.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Producción, pasillos y almacén',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 6,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Perímetro completo',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR 18 canales',
            role: 'Grabación centralizada',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi Pro',
            role: 'Red empresarial',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'ups',
            label: 'UPS Grande',
            role: 'Continuidad operativa',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'high',
          },
        ],
      },
    },
  },
  {
    id: 'colegio',
    label: 'Colegio',
    icon: '🏫',
    description: 'Seguridad para entornos educativos',
    color: 'bg-rose-50',
    accent: 'text-rose-700',
    scales: {
      S: {
        name: 'Sala / Aula',
        description: 'Una sola aula o sala de sistemas. Vigilancia básica.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Aula y acceso',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'low',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red educativa',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Respaldo equipos',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'low',
          },
        ],
      },
      M: {
        name: 'Colegio pequeño',
        description: 'Planta con 5–10 aulas. Pasillos, entrada y patio cubiertos.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Pasillos y recepción',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior',
            role: 'Entrada y cancha',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red educativa',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Continuidad',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Institución educativa grande',
        description: 'Campus universitario o colegio grande. Múltiples plantas y patios.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Aulas, pasillos y lab',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 8,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Entradas y campos',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR grabador',
            role: 'Almacenamiento 24/7',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi Pro',
            role: 'Red institucional',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'ups',
            label: 'UPS Mediana',
            role: 'Protección eléctrica',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'mid',
          },
        ],
      },
    },
  },
  {
    id: 'almacen',
    label: 'Almacén / Bodega',
    icon: '📦',
    description: 'Vigilancia de logística y almacenamiento',
    color: 'bg-slate-50',
    accent: 'text-slate-700',
    scales: {
      S: {
        name: 'Bodega pequeña',
        description: 'Hasta 200m². Entrada, despachos y producto.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Estibas y producto',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior',
            role: 'Portón y cargue',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red operativa',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'low',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Respaldo equipos',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 1,
            priceHint: 'mid',
          },
        ],
      },
      M: {
        name: 'Centro logístico',
        description: '200–800m². Racks, zona de cargue y portería.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Racks y operaciones',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 5,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Patios y camiones',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 2,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi',
            role: 'Red operativa',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'mid',
          },
          {
            id: 'ups',
            label: 'UPS',
            role: 'Backup continuo',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'mid',
          },
        ],
      },
      L: {
        name: 'Bodega industrial',
        description: '+800m². Automatización, vigilancia 360° con NVR.',
        slots: [
          {
            id: 'cam-int',
            label: 'Cámara interior',
            role: 'Todo el piso de bodega',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 8,
            priceHint: 'mid',
          },
          {
            id: 'cam-ext',
            label: 'Cámara exterior PTZ',
            role: 'Perímetro y vías',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 4,
            priceHint: 'high',
          },
          {
            id: 'nvr',
            label: 'NVR 18 canales',
            role: 'Grabación centralizada',
            categorySlug: 'camaras-wifi',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'router',
            label: 'Router WiFi Pro',
            role: 'Red logística',
            categorySlug: 'routers-redes',
            brand: 'IMOU',
            qty: 1,
            priceHint: 'high',
          },
          {
            id: 'ups',
            label: 'UPS Grande',
            role: 'Continuidad total',
            categorySlug: 'energia-respaldo',
            brand: 'FORZA',
            qty: 2,
            priceHint: 'high',
          },
        ],
      },
    },
  },
]
