// Datos mock temporales para desarrollo
export const mockProducts = [
  {
    id: '1',
    name: 'IMOU Ranger Dual Hogar',
    slug: 'imou-ranger-dual-hogar',
    description:
      'Cámara de seguridad WiFi con doble lente para vigilancia completa del hogar',
    price: 89900,
    stock: 15,
    category: 'Cámaras de Seguridad',
    brand: 'IMOU',
    image_url: '/productos/imou/imou_ranger_dual_hogar.jpg',
    featured: true,
    specifications: {
      Resolución: '1080p Full HD',
      Conectividad: 'WiFi 2.4GHz',
      'Visión nocturna': 'Hasta 10 metros',
      Audio: 'Bidireccional',
      Almacenamiento: 'MicroSD hasta 256GB',
    },
  },
  {
    id: '2',
    name: 'TP-Link Archer BE800 WiFi 7',
    slug: 'tplink-archer-be800-wifi7',
    description:
      'Router WiFi 7 de última generación con puertos 10G para máximo rendimiento',
    price: 459900,
    stock: 8,
    category: 'Routers y Networking',
    brand: 'TP-Link',
    image_url:
      '/productos/tplink/Archer_BE800_WiFi_7_Router_with_10G_Ports_3.jpg',
    featured: true,
    specifications: {
      'Estándar WiFi': 'WiFi 7 (BE19000)',
      Puertos: '2x 10G + 4x Gigabit',
      Procesador: 'Quad-core 2.6GHz',
      Antenas: '8 antenas externas',
      Cobertura: 'Hasta 300m²',
    },
  },
  {
    id: '3',
    name: 'Mouse Logitech Gaming LED',
    slug: 'mouse-logitech-gaming-led',
    description:
      'Mouse gaming de alta precisión con iluminación LED RGB personalizable',
    price: 35900,
    stock: 25,
    category: 'Accesorios Gaming',
    brand: 'Logitech',
    image_url: '/productos/Logitech/mouse_logitech_led.png',
    featured: true,
    specifications: {
      DPI: 'Hasta 16,000 DPI',
      Botones: '6 botones programables',
      Iluminación: 'RGB personalizable',
      Conectividad: 'USB con cable trenzado',
      Peso: '95 gramos',
    },
  },
  {
    id: '4',
    name: 'IMOU Cámara Solar Bala',
    slug: 'imou-camara-solar-bala',
    description:
      'Cámara de seguridad exterior con panel solar integrado, completamente inalámbrica',
    price: 129900,
    stock: 12,
    category: 'Cámaras de Seguridad',
    brand: 'IMOU',
    image_url: '/productos/imou/imou_solar_bala.jpg',
    featured: true,
    specifications: {
      Resolución: '2K+ (2304x1296)',
      Alimentación: 'Panel solar + batería 5200mAh',
      Resistencia: 'IP66',
      Detección: 'PIR + AI humana',
      Almacenamiento: 'Cloud + MicroSD',
    },
  },
  {
    id: '5',
    name: 'Forza UPS 1500VA',
    slug: 'forza-ups-1500va',
    description:
      'Sistema de alimentación ininterrumpida para protección de equipos electrónicos',
    price: 189900,
    stock: 10,
    category: 'UPS y Energía',
    brand: 'Forza',
    image_url: '/productos/forza/ups_forza_1500va.jpg',
    featured: false,
    specifications: {
      Potencia: '1500VA / 900W',
      Salidas: '6 tomas con respaldo',
      Batería: 'Sellada libre de mantenimiento',
      'Tiempo respaldo': '10-15 minutos',
      Pantalla: 'LCD con información',
    },
  },
  {
    id: '6',
    name: 'IMOU Panel Solar Z',
    slug: 'imou-panel-solar-z',
    description:
      'Panel solar para cámaras IMOU, instalación fácil y carga continua',
    price: 45900,
    stock: 20,
    category: 'Cámaras de Seguridad',
    brand: 'IMOU',
    image_url: '/productos/imou/imou_panel_solar_Z.jpg',
    featured: false,
    specifications: {
      Potencia: '5.5W',
      Compatibilidad: 'Cámaras IMOU serie Cell',
      Cable: '4 metros incluido',
      Instalación: 'Soporte ajustable',
      Resistencia: 'IP65',
    },
  },
  {
    id: '7',
    name: 'Mercusys Router AC12G',
    slug: 'mercusys-router-ac12g',
    description:
      'Router WiFi AC1200 dual band para uso doméstico y pequeñas oficinas',
    price: 29900,
    stock: 30,
    category: 'Routers y Networking',
    brand: 'Mercusys',
    image_url: '/productos/mercusys/mercusys_ac12g.jpg',
    featured: false,
    specifications: {
      'Estándar WiFi': 'AC1200 (300+867 Mbps)',
      Antenas: '4 antenas externas',
      Puertos: '4 puertos Ethernet',
      Procesador: 'Single-core 775MHz',
      Modos: 'Router/Access Point/Range Extender',
    },
  },
  {
    id: '8',
    name: 'Dahua DVR 8 Canales',
    slug: 'dahua-dvr-8-canales',
    description:
      'Grabador digital de video para sistema de cámaras analógicas y HD-CVI',
    price: 159900,
    stock: 6,
    category: 'Cámaras de Seguridad',
    brand: 'Dahua',
    image_url: '/productos/dahua/dvr_dahua_8ch.jpg',
    featured: false,
    specifications: {
      Canales: '8 canales de video',
      Resolución: 'Hasta 4K por canal',
      Almacenamiento: 'Hasta 2 HDD de 10TB',
      Compresión: 'H.265+/H.264+',
      Red: 'Acceso remoto vía app',
    },
  },
]

export const mockCategories = [
  {
    id: '1',
    name: 'Cámaras de Seguridad',
    slug: 'camaras-seguridad',
    description: 'Sistemas de videovigilancia y cámaras IP',
  },
  {
    id: '2',
    name: 'Routers y Networking',
    slug: 'routers-networking',
    description: 'Equipos de red, routers y switches',
  },
  {
    id: '3',
    name: 'Accesorios Gaming',
    slug: 'accesorios-gaming',
    description: 'Periféricos y accesorios para gaming',
  },
  {
    id: '4',
    name: 'UPS y Energía',
    slug: 'ups-energia',
    description: 'Sistemas de respaldo energético',
  },
]
